name: Ci McSimFin
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: set env variables
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/mc_sim_fin" >> $GITHUB_ENV
      - uses: actions/checkout@master
      - name: install dependencies
        run: pip --disable-pip-version-check --no-cache-dir install -r requirements-dev.txt
      - name: run tests
        run: pytest --cov=./ --flake8
  
  codecov:
    runs-on: ubuntu-latest
    needs: test
    steps:
        # - name: gen codecov report
        #   run: pytest --cov=./ --flake8
        - name: publish on codecov
          uses: codecov/codecov-action@v3
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy to pypi
        if:  startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}